---
- name: Create Switch Configurations with Templates
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Generate configuration for Switches
      template: src=./config_templates/2960template.j2 dest=./configs/{{ item.hostname }}.txt

      with_items:
        - { hostname: "{{hostname}}", ports: "{{ports}}", ipaddress: "{{ip}}", gateway: "{{gw}}", siteid: "{{BU}}" }
          # - { hostname: TEST-SW02, ports: 48, ipaddress: '2.2.2.2', gateway: '2.2.2.1', siteid: 'BU-####' }
...
